<div class="page">
	<div class="block">Стрижаков Александр</div>
	<div class="block">Стрижакова Юлия</div>
	<div class="block">Цветков Михаил</div>
	<div class="block">Самарская Алина</div>
</div>
<div class="page">
	<div class="block">Шиманская Анна</div>
	<div class="block">Фролов Максим</div>
	<div class="block">Фролова Татьяна</div>
	<div class="block">Горенштейн Михаил</div>
</div>
<div class="page">
	<div class="block">Исеева Алла</div>
	<div class="block">Репицкий Сергей</div>
	<div class="block">Довгаль Денис</div>
	<div class="block">Цариковская Галина</div>
</div>
<div class="page">
	<div class="block">Стройло Ирина</div>
	<div class="block">Шпак Альбина</div>
	<div class="block">Иванов Вячеслав</div>
	<div class="block">Рубан Михаил</div>
</div>
<div class="page">
	<div class="block">Некрасова Кристина</div>
	<div class="block">Красавцев Сергей</div>
	<div class="block">Лесных Андрей</div>
	<div class="block">Лесных Марина</div>
</div>
<div class="page">
	<div class="block">Лесных Мишелька</div>
	<div class="block">Людмила Ивановна</div>
	<div class="block">Владимир Андреевич</div>
	<div class="block">Лариса Алексеевна</div>
</div>
<div class="page">
	<div class="block">Анатолий Иванович</div>
	<div class="block">Олег Николаевич</div>
</div>
