<?php print( $this->doctype() ); ?><html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en"><head>
<?php print( $this->headTitle() ); ?>

<?php print( $this->headMeta() ); ?>
	
<?php print( $this->headLink() ); ?>
	
<?php print( $this->headStyle() ); ?>
</head><body><div id="shadowBox" onclick="closeObscureContent();"></div><div id="shadowBoxLoading"></div><div id="shadowBoxWrapper">	<div class="corner lt"></div>	<div class="corner rt"></div>	<div class="shadow right"></div>	<div class="shadowBoxCloseIcon" onclick="closeObscureContent();"></div>	<div id="shadowBoxInnerWrapper">		<div id="shadowBoxContent"></div>		<br class="clearing" />	</div>	<div class="shadow left"></div>	<div class="corner lb"></div>	<div class="corner rb"></div></div><div id="main-block">	<div id="header">		<div id="logo-top"></div>		<div id="logo-middle">			<div id="logo-middle-right">				<?php print( $this->authBlock() ); ?>			</div>			<div id="logo-middle-left"></div>		</div>		<div id="logo-bottom"></div>	</div>	<div id="wrapper">		<div id="container">			<div id="content">							<div id="left">					<table id="menu" cellspacing="0" cellpadding="0">
						<tr>
							<td id="menu-left_title"></td>
							<td id="menu-right_title">
								<a href="<?php print( $this->url( array( 'controller' => 'index' ), 'default', true ) ); ?>"><img id="index-link-img" src="http://images.morgenshtern.com/index-link-img.gif" width="72" height="18" alt="" title="Вернуться на главную" /></a>
								<img src="http://images.morgenshtern.com/winter/star.gif" width="18" height="18" alt="" title="" />
								<a href="http://forum.morgenshtern.com/" class="external"><img id="forum-link-img" src="http://images.morgenshtern.com/forum-link-img.gif" width="58" height="18" alt="" title="Перейти на форум" /></a>
							</td>
						</tr>
						<tr>
							<td class="menu-left">&nbsp;</td>
							<td class="menu-right">
								<div class="menu-title">Клан</div>
								<br /><a href="/" class="menu_link">Новости</a>
								<br /><a href="/charter" class="menu_link">Устав братства</a>
								<br /><a href="/staff" class="menu_link">Состав братства</a>
								<!--<br /><a href="/chivalry" class="menu_link">Рыцари братства</a>-->
								<br /><a href="/history" class="menu_link">История братства</a>
								<br /><a href="/diplomacy" class="menu_link">Дипломатия</a>
								<br /><a href="/vacancy" class="menu_link">Вступление</a>								<br /><a href="/news/add" class="menu_link">Добавить новость</a>
								<br /><a href="/jeremiad" class="menu_link">Подать жалобу</a>
							</td>
						</tr>
						<tr>
							<td class="menu-left">&nbsp;</td>
							<td class="menu-right">
								<div class="menu-title">Библиотека</div>
								<br /><a href="/experience-table" class="menu_link">Таблица опыта</a>
								<!--<br /><a href="/encyclopedia" class="menu_link">Энциклопедия</a>-->
								<!--<br /><a href="/set" class="menu_link">Комплекты</a>-->
								<!--<br /><a href="/paladin" class="menu_link">Ранги паладинов</a>-->
								<!--<br /><a href="/tarman" class="menu_link">Ранги тарманов</a>-->
								<!--<br /><a href="/clans" class="menu_link">Список кланов</a>-->
								<br /><a href="/tower-of-death" class="menu_link">Карта Башни Смерти</a>
								<!--<br /><a href="/bonus/stats" class="menu_link">Статовые бонусы</a>-->
							</td>
						</tr>
						<!--						<tr>
							<td class="menu-left">&nbsp;</td>
							<td class="menu-right">
								<div class="menu-title">Сервисы</div>
								<br /><a href="/staff/allies" class="menu_link">Мониторинг союзников</a>
								<br /><a href="/analize" class="menu_link">Анализатор боя</a>
							</td>
						</tr>						-->
						<!--						<tr>
							<td class="menu-left">&nbsp;</td>
							<td class="menu-right">
								<div class="menu-title">Творчество</div>
								<br /><a href="/articles" class="menu_link">Статьи</a>
								<br /><a href="/poetry" class="menu_link">Стихи и проза</a>
								<br /><a href="/tournament" class="menu_link">Турниры</a>
							</td>
						</tr>
						<tr>
							<td class="menu-left">&nbsp;</td>
							<td class="menu-right">
								<div class="menu-title">Услуги</div>
								<br /><a href="/eurocredits" class="menu_link">Еврокредиты</a>
								<br /><a href="/alchemist" class="menu_link">Алхимики БК</a>
							</td>
						</tr>						-->
						<tr>
							<td id="menu-left-copyright"></td>
							<td id="menu-right-copyright">
								<a href="/it">IT Team</a> &copy; 2005—<?php print( date( 'Y' ) ); ?>
							</td>
						</tr>
						<tr>
							<td id="menu-left_bottom">&nbsp;</td>
							<td id="menu-right_bottom">
								<a href="http://top.combats.com/c.pl?jump" class="external counter"><img src="http://top.combats.com/c.pl?z8" width="88" height="33" alt="Счетчик БК" /></a>
								<a href="http://top.mail.ru/jump?from=980581" class="external counter"><img src="http://d6.cf.be.a0.top.list.ru/counter?id=980581;t=55" height="31" width="88" alt="Рейтинг@Mail.ru" /></a>
							</td>
						</tr>
					</table>				</div>								<div id="main">					<div id="main-content">						<?php print( $this->layout()->content ); ?>					</div>				</div>							</div>		</div>				<!--		<div id="sidebar">			<div id="picture-of-the-day" class="ui-widget-content ui-corner-all right-side-bar">				<h3 class="ui-widget-header ui-corner-all">Картинка дня</h3>				<div>									</div>			</div>		</div>		-->		<div style="height: 0; clear: both;">&nbsp;</div>	</div>	<div id="footerGuarantor">&nbsp;</div></div><div id="footer">При использовании материалов сайта ссылка на www.morgenshtern.com обязательна.</div>
<?php print( $this->headScript() ); ?>

<!-- Yandex.Metrika counter -->
<div style="display:none;"><script type="text/javascript">
(function(w, c) {
    (w[c] = w[c] || []).push(function() {
        try {
            w.yaCounter3769438 = new Ya.Metrika(3769438);
             yaCounter3769438.clickmap(true);
             yaCounter3769438.trackLinks(true);
        
        } catch(e) {}
    });
})(window, 'yandex_metrika_callbacks');
</script></div>
<script src="//mc.yandex.ru/metrika/watch.js" type="text/javascript" defer="defer"></script>
<noscript><div style="position:absolute"><img src="//mc.yandex.ru/watch/3769438" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->
</body></html>
