<fieldset>
	<legend>Авторизация</legend>
	<form id="authorization-form" action="/login" method="post">
		<div>
			<label>Логин: <input type="text" id="nick" name="nick" value="" /></label>
			<br />
			<label>Пароль: <input type="password" id="password" name="password" value="" /></label>
			<br />
			<a href="" id="authorization-forget-password-link">Забыли пароль?</a> 
			<input type="image" id="authorization-submit-button" src="http://images.morgenshtern.com/enter.gif" alt="Авторизация" title="Войти" />
		</div>
	</form>
</fieldset>