<?php print( $this->doctype() ); ?>

<html lang="ru-RU">
<head>
<meta charset="utf-8">
<?php print( $this->headMeta() ); ?>

<?php print( $this->headTitle() ); ?>
	
<?php print( $this->headLink() ); ?>
	
<?php print( $this->headStyle() ); ?>
</head>
<body>

<div id="wrap">
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
                <a class="navbar-brand visible-xs" href="http://lesnykh.ru/">Лесных Илья</a>
                <a class="navbar-brand hidden-xs" href="http://lesnykh.ru/">Персональный сайт Лесных Ильи</a>
            </div>
			<div class="collapse navbar-collapse" id="navbar-collapse">
				<ul class="nav navbar-nav navbar-right">
					<li><a href="//job.lesnykh.ru/">Веб разработчик</a></li>
				</ul>
			</div>
        </div>
    </nav>
    <div class="container">
<?php print( $this->layout()->content ); ?>
    </div>
</div>

<footer>
    <div class="container text-center">2005 &mdash; <?=date('Y')?> &copy; Лесных Илья</div>
</footer>

<?php print( $this->headScript() ); ?>

<!-- Yandex.Metrika counter -->
<script src="//mc.yandex.ru/metrika/watch.js" type="text/javascript"></script>
<script type="text/javascript">
try { var yaCounter1959736 = new Ya.Metrika({id:1959736,
          webvisor:true,
          clickmap:true,
          trackLinks:true,
          accurateTrackBounce:true});
} catch(e) { }
</script>
<noscript><div><img src="//mc.yandex.ru/watch/1959736" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
<!-- /Yandex.Metrika counter -->

</body>
</html>
