<div id="content-title">API</div>

<p class="paragraph">
	Данная страница содержит общие сведения о предоставляемом кланом <strong>Morgenshtern</strong> <abbr title="Application Programming Interface">API</abbr> 
	для получения полного и актуального списка всех чаров указанного клана. С помощью данного 
	<abbr title="Application Programming Interface">API</abbr> возможна реализация, например, функционала «<b>Состав клана</b>» на клан–сайте.
</p>

<h3>Как это работает</h3>

<p class="paragraph">
	Имея доступ к нашему <abbr title="Application Programming Interface">API</abbr>, клановый веб–разработчик пишет на своём сервере скрипт, 
	который подключается к нашему серверу и запрашивает страничку с <abbr title="Application Programming Interface">API</abbr>, передавая 
	в качестве параметров ключ, название клана и желаемый формат ответа. Например, для того чтобы получить состав клана 
	<strong>Morgenshtern</strong> в формате xml необходимо использовать следующий url: 
	<code>http://www.morgenshtern.com/api/staff/clan/Morgenshtern/key/<i>1234567890</i>/format/xml</code>, где <i>1234567890</i> — ключ соединения.
</p>

<h3>Как получить доступ к API</h3>

<p class="paragraph">
	Глава клана <a href="http://forum.morgenshtern.com/index.php?act=Reg&amp;CODE=00">регистрируется</a> у нас на сайте, если он еще этого не сделал. 
	Далее переходит на <a href="/api.html">страницу API</a> у нас на сайте и <a href="/api/registration">подает заявку на подключения API</a> 
	для своего клана. Все заявки обрабатываются вручную. Любая заявка может быть отклонена без объяснения причин. Обязательным условием для подачи 
	заявки является принятие «<a href="/api/agreement">Пользовательского соглашения о правилах использования кланового API</a>», текст которого будет приведен ниже.
</p>

<h3>Поддерживаемые форматы ответа</h3>

<p class="paragraph">
	На данный момент поддерживается только ответ в формате <abbr title="eXtensible Markup Language">XML</abbr> (text/xml) в кодировке 
	utf-8. В будущем планируется так же поддержка других форматов передачи данных, например <abbr title="Java Script Object Notation">JSON</abbr>.
</p>

<h3>Формат корректного ответа</h3>

<p class="paragraph">
	В ответ на Ваше обращение наш API вернет Вам ответ в следующем формате:
	<pre>
&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;clan&gt;
	&lt;title&gt;Название вашего клана&lt;/title&gt;
	&lt;staff&gt;
		&lt;char&gt;
			&lt;id&gt;ID чара в БК&lt;/id&gt;
			&lt;nick&gt;Ник чара в БК&lt;/nick&gt;
			&lt;level&gt;Уровень чара в БК&lt;/level&gt;
			&lt;city&gt;Город нахождения чара в БК&lt;/city&gt;
			&lt;rank&gt;Статус в чара клане (прописанный в инфо)&lt;/rank&gt;
			&lt;online&gt;true – если чар онлайн и false иначе&lt;/online&gt;
			&lt;room&gt;Комната, в которой находится чар&lt;/room&gt;
			&lt;battle&gt;ID битвы, в которой участвует чар&lt;/battle&gt;
		&lt;/char&gt;
		&lt;char&gt;
			тоже самое для следующего чара...
		&lt;/char&gt;
	&lt;/staff&gt;
&lt;/clan&gt;
	</pre>
	Стоит отметить, что теги rank, room и battle могут быть пустыми, если соответствующее значение отсутствует в инфо чара.
	Так же важно заметить, что глава клана всегда идет первым чаром!
</p>

<h3>Формат ошибочного ответа</h3>

<p class="paragraph">
	Но к несчастью не всегда бывает все так радужно. Случается так, что по каким–либо причинам наш скрипт не может вернуть правильный ответ, 
	тогда будет сгенерирована ошибка, которая вернет данные в том же формате, в котором они запрашивались, но с соответствующей пометкой об ошибке.
	<pre>
&lt;?xml version="1.0" encoding="utf-8"?&gt;
&lt;error&gt;
	&lt;code&gt;Код ошибки&lt;/code&gt;
&lt;/error&gt;
	</pre>
</p>

<h3>Коды ошибок</h3>

<p class="paragraph">
	Ниже приведены все возможные коды ошибок и их описания:
	<table>
		<thead>
			<tr>
				<th>Код</th>
				<th>Описание</th>
			</tr>
		</thead>
		<tbody>
			<tr>
				<td>1</td>
				<td>Заявки на использование API от этого клана не поступало</td>
			</tr>
			<tr>
				<td>2</td>
				<td>Ваша заявки на использование API еще не подтверждена</td>
			</tr>
			<tr>
				<td>3</td>
				<td>Не верно введен авторизационный ключ</td>
			</tr>
			<tr>
				<td>4</td>
				<td>Указанный клан не найден в БК</td>
			</tr>
			<tr>
				<td>5</td>
				<td>Сервер БК недоступен (Service Unavailable)</td>
			</tr>
			<tr>
				<td>-1</td>
				<td>Наш IP был временно заблокирован сервером БК</td>
			</tr>
			<tr>
				<td>-2</td>
				<td>Указан неверный формат ответа</td>
			</tr>
			<tr>
				<td>-100</td>
				<td>Произошла непредвиденная ошибка</td>
			</tr>
		</tbody>
	</table>
</p>

<h3></h3>

<p class="paragraph">
	
</p>